blank_issue_enabled: false
contact_links:
  - name: "Area de TI - Desarrollo, Infraestructura, Ciberseguridad, Datos y Soporte."
    url: ""
    about: "Seccion de soporte para la configuracion de Incidencias del Area."